# Generated by Django 6.0.1 on 2026-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='green_points',
            field=models.IntegerField(default=0),
        ),
    ]
