# Generated by Django 6.0.1 on 2026-03-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='phone',
        ),
        migrations.AddField(
            model_name='complaint',
            name='garbage_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='severity',
            field=models.CharField(default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
